### ISSUE TITLE
power loss recovery doesn't work the recovery file is written to the sd but after the power comes back there is no summary menu

### ISSUE THREAD

**Issue by ivograca** [le3tspeak/Marlin-2.0.X-MKS-Robin-Nano#10]
### Steps to Reproduce

1. [First Step] use that configurations 
2. [Second Step] use M413 S1 to activate power loss recovery 
3. [and so on...] print any test and unplug in midle of print after first or second layer and turn on again. when turning on the resume menu does not appear you can see in the SD the file was created

**Expected behavior:** [What you expect to happen] resume print on screen menu

**Actual behavior:** [What actually happens] nothing

#### Additional Information
Marlin version 2.0.5.3
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.
[Configuration.zip](https://github.com/le3tspeak/Marlin-2.0.X-MKS-Robin-Nano/files/4688055/Configuration.zip)

**Comment by le3tspeak** [comment]
No Configuration.h and Configuration_adv.h files added.
Which version?

**Comment by ivograca** [comment]
my mistake. already updated with all the information thanks for your work

**Comment by ivograca** [comment]
> No Configuration.h and Configuration_adv.h files added.
> Which version?

my mistake. already updated with all the information thanks for your work

**Comment by le3tspeak** [comment]
MKS Robin Nano is not compatible with the function in the currently known bug in 2.0.5.3
