### ISSUE TITLE
can not compile

### ISSUE THREAD

**Issue by ivograca** [le3tspeak/Marlin-2.0.X-MKS-Robin-Nano#13]
### Description marlin does not compile

Marlin\src\inc/Conditionals_post.h:180:22: error: 'X_HOME_DIR' was not declared in this scope
   #define X_END_POS (X_HOME_DIR < 0 ? X_MIN_POS : X_MAX_POS)
                      ^
Marlin\src\inc/../core/macros.h:397:26: note: in definition of macro 'THIRD'
 #define THIRD(a,b,c,...) c
                          ^
Marlin\src\inc/../core/macros.h:192:29: note: in expansion of macro '___TERN'
 #define __TERN(T,V...)      ___TERN(_CAT(_NO,T),V)  // Prepend '_NO' to get '_NOT_0' or '_NOT_1'
                             ^~~~~~~
Marlin\src\inc/../core/macros.h:191:29: note: in expansion of macro '__TERN'
 #define _TERN(E,V...)       __TERN(_CAT(T_,E),V)    // Prepend 'T_' to get 'T_0' or 'T_1'
                             ^~~~~~
Marlin\src\inc/../core/macros.h:187:29: note: in expansion of macro '_TERN'
 #define TERN(O,A,B)         _TERN(_ENA_1(O),B,A)    // OPTION converted to '0' or '1'
                             ^~~~~
Marlin\src\inc/Conditionals_post.h:184:24: note: in expansion of macro 'TERN'
     #define X_HOME_POS TERN(DELTA, X_MIN_POS + (X_BED_SIZE) * 0.5, X_END_POS)
                        ^~~~
Marlin\src\inc/Conditionals_post.h:184:68: note: in expansion of macro 'X_END_POS'
     #define X_HOME_POS TERN(DELTA, X_MIN_POS + (X_BED_SIZE) * 0.5, X_END_POS)
                                                                    ^~~~~~~~~
Marlin\src\lcd/../module/motion.h:116:49: note: in expansion of macro 'X_HOME_POS'
     static const XYZval<T> NAME##_P PROGMEM = { X_##OPT, Y_##OPT, Z_##OPT }; \
                                                 ^~
Marlin\src\lcd/../module/motion.h:121:1: note: in expansion of macro 'XYZ_DEFS'
 XYZ_DEFS(float, base_home_pos,  HOME_POS);
 ^~~~~~~~
Marlin\src\inc/Conditionals_post.h:180:22: note: suggested alternative: 'X_HOME_POS'
   #define X_END_POS (X_HOME_DIR < 0 ? X_MIN_POS : X_MAX_POS)
                      ^
Marlin\src\inc/../core/macros.h:397:26: note: in definition of macro 'THIRD'
 #define THIRD(a,b,c,...) c
                          ^
Marlin\src\inc/../core/macros.h:192:29: note: in expansion of macro '___TERN'
 #define __TERN(T,V...)      ___TERN(_CAT(_NO,T),V)  // Prepend '_NO' to get '_NOT_0' or '_NOT_1'
                             ^~~~~~~
Marlin\src\inc/../core/macros.h:191:29: note: in expansion of macro '__TERN'
 #define _TERN(E,V...)       __TERN(_CAT(T_,E),V)    // Prepend 'T_' to get 'T_0' or 'T_1'
                             ^~~~~~
Marlin\src\inc/../core/macros.h:187:29: note: in expansion of macro '_TERN'
 #define TERN(O,A,B)         _TERN(_ENA_1(O),B,A)    // OPTION converted to '0' or '1'
                             ^~~~~
Marlin\src\inc/Conditionals_post.h:184:24: note: in expansion of macro 'TERN'
     #define X_HOME_POS TERN(DELTA, X_MIN_POS + (X_BED_SIZE) * 0.5, X_END_POS)
                        ^~~~
Marlin\src\inc/Conditionals_post.h:184:68: note: in expansion of macro 'X_END_POS'
     #define X_HOME_POS TERN(DELTA, X_MIN_POS + (X_BED_SIZE) * 0.5, X_END_POS)
                                                                    ^~~~~~~~~
Marlin\src\lcd/../module/motion.h:116:49: note: in expansion of macro 'X_HOME_POS'
     static const XYZval<T> NAME##_P PROGMEM = { X_##OPT, Y_##OPT, Z_##OPT }; \
                                                 ^~
Marlin\src\lcd/../module/motion.h:121:1: note: in expansion of macro 'XYZ_DEFS'
 XYZ_DEFS(float, base_home_pos,  HOME_POS);
 ^~~~~~~~
Marlin\src\inc/Conditionals_post.h:191:22: error: 'Y_HOME_DIR' was not declared in this scope
   #define Y_END_POS (Y_HOME_DIR < 0 ? Y_MIN_POS : Y_MAX_POS)
                      ^
Marlin\src\inc/../core/macros.h:397:26: note: in definition of macro 'THIRD'
 #define THIRD(a,b,c,...) c
                          ^
Marlin\src\inc/../core/macros.h:192:29: note: in expansion of macro '___TERN'
 #define __TERN(T,V...)      ___TERN(_CAT(_NO,T),V)  // Prepend '_NO' to get '_NOT_0' or '_NOT_1'
                             ^~~~~~~
Marlin\src\inc/../core/macros.h:191:29: note: in expansion of macro '__TERN'
 #define _TERN(E,V...)       __TERN(_CAT(T_,E),V)    // Prepend 'T_' to get 'T_0' or 'T_1'
                             ^~~~~~
Marlin\src\inc/../core/macros.h:187:29: note: in expansion of macro '_TERN'
 #define TERN(O,A,B)         _TERN(_ENA_1(O),B,A)    // OPTION converted to '0' or '1'
                             ^~~~~
Marlin\src\inc/Conditionals_post.h:195:24: note: in expansion of macro 'TERN'
     #define Y_HOME_POS TERN(DELTA, Y_MIN_POS + (Y_BED_SIZE) * 0.5, Y_END_POS)
                        ^~~~
Marlin\src\inc/Conditionals_post.h:195:68: note: in expansion of macro 'Y_END_POS'
     #define Y_HOME_POS TERN(DELTA, Y_MIN_POS + (Y_BED_SIZE) * 0.5, Y_END_POS)
                                                                    ^~~~~~~~~
Marlin\src\lcd/../module/motion.h:116:58: note: in expansion of macro 'Y_HOME_POS'
     static const XYZval<T> NAME##_P PROGMEM = { X_##OPT, Y_##OPT, Z_##OPT }; \
                                                          ^~
Marlin\src\lcd/../module/motion.h:121:1: note: in expansion of macro 'XYZ_DEFS'
 XYZ_DEFS(float, base_home_pos,  HOME_POS);
 ^~~~~~~~
Marlin\src\inc/Conditionals_post.h:191:22: note: suggested alternative: 'Y_HOME_POS'
   #define Y_END_POS (Y_HOME_DIR < 0 ? Y_MIN_POS : Y_MAX_POS)
                      ^
Marlin\src\inc/../core/macros.h:397:26: note: in definition of macro 'THIRD'
 #define THIRD(a,b,c,...) c
                          ^
Marlin\src\inc/../core/macros.h:192:29: note: in expansion of macro '___TERN'
 #define __TERN(T,V...)      ___TERN(_CAT(_NO,T),V)  // Prepend '_NO' to get '_NOT_0' or '_NOT_1'
                             ^~~~~~~
Marlin\src\inc/../core/macros.h:191:29: note: in expansion of macro '__TERN'
 #define _TERN(E,V...)       __TERN(_CAT(T_,E),V)    // Prepend 'T_' to get 'T_0' or 'T_1'
                             ^~~~~~
Marlin\src\inc/../core/macros.h:187:29: note: in expansion of macro '_TERN'
 #define TERN(O,A,B)         _TERN(_ENA_1(O),B,A)    // OPTION converted to '0' or '1'
                             ^~~~~
Marlin\src\inc/Conditionals_post.h:195:24: note: in expansion of macro 'TERN'
     #define Y_HOME_POS TERN(DELTA, Y_MIN_POS + (Y_BED_SIZE) * 0.5, Y_END_POS)
                        ^~~~
Marlin\src\inc/Conditionals_post.h:195:68: note: in expansion of macro 'Y_END_POS'
     #define Y_HOME_POS TERN(DELTA, Y_MIN_POS + (Y_BED_SIZE) * 0.5, Y_END_POS)
                                                                    ^~~~~~~~~
Marlin\src\lcd/../module/motion.h:116:58: note: in expansion of macro 'Y_HOME_POS'
     static const XYZval<T> NAME##_P PROGMEM = { X_##OPT, Y_##OPT, Z_##OPT }; \
                                                          ^~
Marlin\src\lcd/../module/motion.h:121:1: note: in expansion of macro 'XYZ_DEFS'
 XYZ_DEFS(float, base_home_pos,  HOME_POS);
 ^~~~~~~~
In file included from Marlin\src\inc/MarlinConfig.h:35:0,
                 from Marlin\src\MarlinCore.h:24,
                 from Marlin\src\MarlinCore.cpp:31:
Marlin\src\inc/Conditionals_post.h:202:23: error: 'Z_HOME_DIR' was not declared in this scope
   #define Z_HOME_POS (Z_HOME_DIR < 0 ? Z_MIN_POS : Z_MAX_POS)
                       ^
Marlin\src\lcd/../module/motion.h:116:67: note: in expansion of macro 'Z_HOME_POS'
     static const XYZval<T> NAME##_P PROGMEM = { X_##OPT, Y_##OPT, Z_##OPT }; \
                                                                   ^~
Marlin\src\lcd/../module/motion.h:121:1: note: in expansion of macro 'XYZ_DEFS'
 XYZ_DEFS(float, base_home_pos,  HOME_POS);
 ^~~~~~~~
Marlin\src\inc/Conditionals_post.h:202:23: note: suggested alternative: 'Z_HOME_POS'
   #define Z_HOME_POS (Z_HOME_DIR < 0 ? Z_MIN_POS : Z_MAX_POS)
                       ^
Marlin\src\lcd/../module/motion.h:116:67: note: in expansion of macro 'Z_HOME_POS'
     static const XYZval<T> NAME##_P PROGMEM = { X_##OPT, Y_##OPT, Z_##OPT }; \
                                                                   ^~
Marlin\src\lcd/../module/motion.h:121:1: note: in expansion of macro 'XYZ_DEFS'
 XYZ_DEFS(float, base_home_pos,  HOME_POS);
 ^~~~~~~~
In file included from Marlin\src\lcd/ultralcd.h:58:0,
                 from Marlin\src\MarlinCore.cpp:42:
Marlin\src\lcd/../module/motion.h: In function 'signed char home_dir(AxisEnum)':
Marlin\src\lcd/../module/motion.h:116:49: error: 'X_HOME_DIR' was not declared in this scope
     static const XYZval<T> NAME##_P PROGMEM = { X_##OPT, Y_##OPT, Z_##OPT }; \
                                                 ^
Marlin\src\lcd/../module/motion.h:123:1: note: in expansion of macro 'XYZ_DEFS'
 XYZ_DEFS(signed char, home_dir, HOME_DIR);
 ^~~~~~~~
In file included from Marlin\src\feature\../inc/../core/boards.h:24:0,
                 from Marlin\src\feature\../inc/MarlinConfigPre.h:35,
                 from Marlin\src\feature\../inc/MarlinConfig.h:28,
                 from Marlin\src\feature\babystep.cpp:23:
Marlin\src\feature\../module/motion.h: In function 'float base_home_pos(AxisEnum)':
Marlin\src\feature\../inc/Conditionals_post.h:180:22: error: 'X_HOME_DIR' was not declared in this scope
   #define X_END_POS (X_HOME_DIR < 0 ? X_MIN_POS : X_MAX_POS)
                      ^
Marlin\src\feature\../inc/../core/macros.h:397:26: note: in definition of macro 'THIRD'
 #define THIRD(a,b,c,...) c
                          ^
Marlin\src\feature\../inc/../core/macros.h:192:29: note: in expansion of macro '___TERN'
 #define __TERN(T,V...)      ___TERN(_CAT(_NO,T),V)  // Prepend '_NO' to get '_NOT_0' or '_NOT_1'
                             ^~~~~~~
Marlin\src\feature\../inc/../core/macros.h:191:29: note: in expansion of macro '__TERN'
 #define _TERN(E,V...)       __TERN(_CAT(T_,E),V)    // Prepend 'T_' to get 'T_0' or 'T_1'
                             ^~~~~~
Marlin\src\feature\../inc/../core/macros.h:187:29: note: in expansion of macro '_TERN'
 #define TERN(O,A,B)         _TERN(_ENA_1(O),B,A)    // OPTION converted to '0' or '1'
                             ^~~~~
Marlin\src\feature\../inc/Conditionals_post.h:184:24: note: in expansion of macro 'TERN'
     #define X_HOME_POS TERN(DELTA, X_MIN_POS + (X_BED_SIZE) * 0.5, X_END_POS)
                        ^~~~
Marlin\src\feature\../inc/Conditionals_post.h:184:68: note: in expansion of macro 'X_END_POS'
     #define X_HOME_POS TERN(DELTA, X_MIN_POS + (X_BED_SIZE) * 0.5, X_END_POS)
                                                                    ^~~~~~~~~
Marlin\src\feature\../module/motion.h:116:49: note: in expansion of macro 'X_HOME_POS'
     static const XYZval<T> NAME##_P PROGMEM = { X_##OPT, Y_##OPT, Z_##OPT }; \
                                                 ^~
Marlin\src\feature\../module/motion.h:121:1: note: in expansion of macro 'XYZ_DEFS'
 XYZ_DEFS(float, base_home_pos,  HOME_POS);
 ^~~~~~~~
Marlin\src\lcd/../module/motion.h:116:49: note: suggested alternative: 'X_HOME_POS'
     static const XYZval<T> NAME##_P PROGMEM = { X_##OPT, Y_##OPT, Z_##OPT }; \
                                                 ^
Marlin\src\lcd/../module/motion.h:123:1: note: in expansion of macro 'XYZ_DEFS'
 XYZ_DEFS(signed char, home_dir, HOME_DIR);
 ^~~~~~~~
Marlin\src\lcd/../module/motion.h:116:58: error: 'Y_HOME_DIR' was not declared in this scope
     static const XYZval<T> NAME##_P PROGMEM = { X_##OPT, Y_##OPT, Z_##OPT }; \
                                                          ^
Marlin\src\lcd/../module/motion.h:123:1: note: in expansion of macro 'XYZ_DEFS'
 XYZ_DEFS(signed char, home_dir, HOME_DIR);
 ^~~~~~~~
Marlin\src\feature\../inc/Conditionals_post.h:180:22: note: suggested alternative: 'X_HOME_POS'
   #define X_END_POS (X_HOME_DIR < 0 ? X_MIN_POS : X_MAX_POS)
                      ^
Marlin\src\feature\../inc/../core/macros.h:397:26: note: in definition of macro 'THIRD'
 #define THIRD(a,b,c,...) c
                          ^
Marlin\src\feature\../inc/../core/macros.h:192:29: note: in expansion of macro '___TERN'
 #define __TERN(T,V...)      ___TERN(_CAT(_NO,T),V)  // Prepend '_NO' to get '_NOT_0' or '_NOT_1'
                             ^~~~~~~
Marlin\src\feature\../inc/../core/macros.h:191:29: note: in expansion of macro '__TERN'
 #define _TERN(E,V...)       __TERN(_CAT(T_,E),V)    // Prepend 'T_' to get 'T_0' or 'T_1'
                             ^~~~~~
Marlin\src\feature\../inc/../core/macros.h:187:29: note: in expansion of macro '_TERN'
 #define TERN(O,A,B)         _TERN(_ENA_1(O),B,A)    // OPTION converted to '0' or '1'
                             ^~~~~
Marlin\src\feature\../inc/Conditionals_post.h:184:24: note: in expansion of macro 'TERN'
     #define X_HOME_POS TERN(DELTA, X_MIN_POS + (X_BED_SIZE) * 0.5, X_END_POS)
                        ^~~~
Marlin\src\feature\../inc/Conditionals_post.h:184:68: note: in expansion of macro 'X_END_POS'
     #define X_HOME_POS TERN(DELTA, X_MIN_POS + (X_BED_SIZE) * 0.5, X_END_POS)
                                                                    ^~~~~~~~~
Marlin\src\feature\../module/motion.h:116:49: note: in expansion of macro 'X_HOME_POS'
     static const XYZval<T> NAME##_P PROGMEM = { X_##OPT, Y_##OPT, Z_##OPT }; \
                                                 ^~
Marlin\src\feature\../module/motion.h:121:1: note: in expansion of macro 'XYZ_DEFS'
 XYZ_DEFS(float, base_home_pos,  HOME_POS);
 ^~~~~~~~
Marlin\src\lcd/../module/motion.h:116:58: note: suggested alternative: 'Y_HOME_POS'
     static const XYZval<T> NAME##_P PROGMEM = { X_##OPT, Y_##OPT, Z_##OPT }; \
                                                          ^
Marlin\src\lcd/../module/motion.h:123:1: note: in expansion of macro 'XYZ_DEFS'
 XYZ_DEFS(signed char, home_dir, HOME_DIR);
 ^~~~~~~~
compilation terminated due to -fmax-errors=5.
Marlin\src\feature\../inc/Conditionals_post.h:191:22: error: 'Y_HOME_DIR' was not declared in this scope
   #define Y_END_POS (Y_HOME_DIR < 0 ? Y_MIN_POS : Y_MAX_POS)
                      ^
Marlin\src\feature\../inc/../core/macros.h:397:26: note: in definition of macro 'THIRD'
 #define THIRD(a,b,c,...) c
                          ^
Marlin\src\feature\../inc/../core/macros.h:192:29: note: in expansion of macro '___TERN'
 #define __TERN(T,V...)      ___TERN(_CAT(_NO,T),V)  // Prepend '_NO' to get '_NOT_0' or '_NOT_1'
                             ^~~~~~~
Marlin\src\feature\../inc/../core/macros.h:191:29: note: in expansion of macro '__TERN'
 #define _TERN(E,V...)       __TERN(_CAT(T_,E),V)    // Prepend 'T_' to get 'T_0' or 'T_1'
                             ^~~~~~
Marlin\src\feature\../inc/../core/macros.h:187:29: note: in expansion of macro '_TERN'
 #define TERN(O,A,B)         _TERN(_ENA_1(O),B,A)    // OPTION converted to '0' or '1'
                             ^~~~~
Marlin\src\feature\../inc/Conditionals_post.h:195:24: note: in expansion of macro 'TERN'
     #define Y_HOME_POS TERN(DELTA, Y_MIN_POS + (Y_BED_SIZE) * 0.5, Y_END_POS)
                        ^~~~
Marlin\src\feature\../inc/Conditionals_post.h:195:68: note: in expansion of macro 'Y_END_POS'
     #define Y_HOME_POS TERN(DELTA, Y_MIN_POS + (Y_BED_SIZE) * 0.5, Y_END_POS)
                                                                    ^~~~~~~~~
Marlin\src\feature\../module/motion.h:116:58: note: in expansion of macro 'Y_HOME_POS'
     static const XYZval<T> NAME##_P PROGMEM = { X_##OPT, Y_##OPT, Z_##OPT }; \
                                                          ^~
Marlin\src\feature\../module/motion.h:121:1: note: in expansion of macro 'XYZ_DEFS'
 XYZ_DEFS(float, base_home_pos,  HOME_POS);
 ^~~~~~~~
Marlin\src\feature\../inc/Conditionals_post.h:191:22: note: suggested alternative: 'Y_HOME_POS'
   #define Y_END_POS (Y_HOME_DIR < 0 ? Y_MIN_POS : Y_MAX_POS)
                      ^
Marlin\src\feature\../inc/../core/macros.h:397:26: note: in definition of macro 'THIRD'
 #define THIRD(a,b,c,...) c
                          ^
Marlin\src\feature\../inc/../core/macros.h:192:29: note: in expansion of macro '___TERN'
 #define __TERN(T,V...)      ___TERN(_CAT(_NO,T),V)  // Prepend '_NO' to get '_NOT_0' or '_NOT_1'
                             ^~~~~~~
Marlin\src\feature\../inc/../core/macros.h:191:29: note: in expansion of macro '__TERN'
 #define _TERN(E,V...)       __TERN(_CAT(T_,E),V)    // Prepend 'T_' to get 'T_0' or 'T_1'
                             ^~~~~~
Marlin\src\feature\../inc/../core/macros.h:187:29: note: in expansion of macro '_TERN'
 #define TERN(O,A,B)         _TERN(_ENA_1(O),B,A)    // OPTION converted to '0' or '1'
                             ^~~~~
Marlin\src\feature\../inc/Conditionals_post.h:195:24: note: in expansion of macro 'TERN'
     #define Y_HOME_POS TERN(DELTA, Y_MIN_POS + (Y_BED_SIZE) * 0.5, Y_END_POS)
                        ^~~~
Marlin\src\feature\../inc/Conditionals_post.h:195:68: note: in expansion of macro 'Y_END_POS'
     #define Y_HOME_POS TERN(DELTA, Y_MIN_POS + (Y_BED_SIZE) * 0.5, Y_END_POS)
                                                                    ^~~~~~~~~
Marlin\src\feature\../module/motion.h:116:58: note: in expansion of macro 'Y_HOME_POS'
     static const XYZval<T> NAME##_P PROGMEM = { X_##OPT, Y_##OPT, Z_##OPT }; \
                                                          ^~
Marlin\src\feature\../module/motion.h:121:1: note: in expansion of macro 'XYZ_DEFS'
 XYZ_DEFS(float, base_home_pos,  HOME_POS);
 ^~~~~~~~
In file included from Marlin\src\feature\../inc/MarlinConfig.h:35:0,
                 from Marlin\src\feature\babystep.cpp:23:
Marlin\src\feature\../inc/Conditionals_post.h:202:23: error: 'Z_HOME_DIR' was not declared in this scope
   #define Z_HOME_POS (Z_HOME_DIR < 0 ? Z_MIN_POS : Z_MAX_POS)
                       ^
Marlin\src\feature\../module/motion.h:116:67: note: in expansion of macro 'Z_HOME_POS'
     static const XYZval<T> NAME##_P PROGMEM = { X_##OPT, Y_##OPT, Z_##OPT }; \
                                                                   ^~
Marlin\src\feature\../module/motion.h:121:1: note: in expansion of macro 'XYZ_DEFS'
 XYZ_DEFS(float, base_home_pos,  HOME_POS);
 ^~~~~~~~
Marlin\src\feature\../inc/Conditionals_post.h:202:23: note: suggested alternative: 'Z_HOME_POS'
   #define Z_HOME_POS (Z_HOME_DIR < 0 ? Z_MIN_POS : Z_MAX_POS)
                       ^
Marlin\src\feature\../module/motion.h:116:67: note: in expansion of macro 'Z_HOME_POS'
     static const XYZval<T> NAME##_P PROGMEM = { X_##OPT, Y_##OPT, Z_##OPT }; \
                                                                   ^~
Marlin\src\feature\../module/motion.h:121:1: note: in expansion of macro 'XYZ_DEFS'
 XYZ_DEFS(float, base_home_pos,  HOME_POS);
 ^~~~~~~~
In file included from Marlin\src\feature\../module/planner.h:46:0,
                 from Marlin\src\feature\babystep.cpp:29:
Marlin\src\feature\../module/motion.h: In function 'signed char home_dir(AxisEnum)':
Marlin\src\feature\../module/motion.h:116:49: error: 'X_HOME_DIR' was not declared in this scope
     static const XYZval<T> NAME##_P PROGMEM = { X_##OPT, Y_##OPT, Z_##OPT }; \
                                                 ^
Marlin\src\feature\../module/motion.h:123:1: note: in expansion of macro 'XYZ_DEFS'
 XYZ_DEFS(signed char, home_dir, HOME_DIR);
 ^~~~~~~~
Marlin\src\feature\../module/motion.h:116:49: note: suggested alternative: 'X_HOME_POS'
     static const XYZval<T> NAME##_P PROGMEM = { X_##OPT, Y_##OPT, Z_##OPT }; \
                                                 ^
Marlin\src\feature\../module/motion.h:123:1: note: in expansion of macro 'XYZ_DEFS'
 XYZ_DEFS(signed char, home_dir, HOME_DIR);
 ^~~~~~~~
Marlin\src\feature\../module/motion.h:116:58: error: 'Y_HOME_DIR' was not declared in this scope
     static const XYZval<T> NAME##_P PROGMEM = { X_##OPT, Y_##OPT, Z_##OPT }; \
                                                          ^
Marlin\src\feature\../module/motion.h:123:1: note: in expansion of macro 'XYZ_DEFS'
 XYZ_DEFS(signed char, home_dir, HOME_DIR);
 ^~~~~~~~
Marlin\src\feature\../module/motion.h:116:58: note: suggested alternative: 'Y_HOME_POS'
     static const XYZval<T> NAME##_P PROGMEM = { X_##OPT, Y_##OPT, Z_##OPT }; \
                                                          ^
Marlin\src\feature\../module/motion.h:123:1: note: in expansion of macro 'XYZ_DEFS'
 XYZ_DEFS(signed char, home_dir, HOME_DIR);
 ^~~~~~~~
compilation terminated due to -fmax-errors=5.
*** [.pio\build\mks_robin_nano\src\src\MarlinCore.cpp.o] Error 1
*** [.pio\build\mks_robin_nano\src\src\feature\babystep.cpp.o] Error 1

**Actual behavior:** just configure for sapphire plus and Fix mounted probe 

#### Additional Information

* Include a ZIP 

[Configuration.zip](https://github.com/le3tspeak/Marlin-2.0.X-MKS-Robin-Nano/files/4694985/Configuration.zip)
[Configuration_adv.zip](https://github.com/le3tspeak/Marlin-2.0.X-MKS-Robin-Nano/files/4694987/Configuration_adv.zip)

**Comment by le3tspeak** [comment]
Make a New Git Clone
