### ISSUE TITLE
[FR] ENABLE LA in Build but set to 0

### ISSUE THREAD

**Issue by thierryzoller** [le3tspeak/Marlin-2.0.X-MKS-Robin-Nano#17]
Please enable LA in build and set it to 0, so that those that want to experiment can.

**Comment by Miraculix200** [comment]
LA doesn't play nice with S_CURVE, so he disabled it. There's no way to turn off S_CURVE via gcode

**Comment by thierryzoller** [comment]
Thanks Miraculix200, my suggestion is to set LA to 0 as compile support but disable it. Users that want to experiment can set it to another value.

PS - JD has problems aswell, but is enabled.

**Comment by thierryzoller** [comment]
I enabled LA and found 0.74 being best. However there was no major difference in results but the extruder did a lot more work. Set it to 0 now.
