### ISSUE TITLE
[BUG] Judder resulting from usage of JD, please revert to Classical Jerk

### ISSUE THREAD

**Issue by thierryzoller** [le3tspeak/Marlin-2.0.X-MKS-Robin-Nano#19]
Printer: Sapphire PRO
**Proposed solution:** Please revert back to classic Jerk, the only jerk control that works as it stands. Or try bugfix2

Link to Marlin Bugs/Issues :
https://github.com/MarlinFirmware/Marlin/issues/18186

Printing circles results in quite severe XY Judder ruining the print.

Print the attached shows in the first layers (big circle)
[judder_test_initial layers.zip](https://github.com/le3tspeak/Marlin-2.0.X-MKS-Robin-Nano/files/4753563/judder_test_initial.layers.zip)

**Comment by thierryzoller** [comment]
https://github.com/MarlinFirmware/Marlin/issues/18186

**Comment by qwewer0** [comment]
Did you try the latest bugfix version?

**Comment by le3tspeak** [comment]
The G code is not an everyday situation, however, this has been extremely exaggerated. In Cura, set the values for maximum resolution, movement resolution, deviation and the problem is gone in your JD setting, and here is a better example for printing circles, the original one Gcode where you linked has 6894KB and a correctly issued GCode for the firmware has only 741KB and the stuttering no longer exists try the G code yourself
[judder_test_initial_layers.aw.zip](https://github.com/le3tspeak/Marlin-2.0.X-MKS-Robin-Nano/files/4754319/judder_test_initial_layers.aw.zip)

**Comment by thierryzoller** [comment]
I am not sure I understand what your point is. You say this is not an "everyday situatuion". That's exactly what it is. The attached is a mould of mine and these are circular shaped. So this _is_ an everyday problem.

I am also not sure what you mean by "a correctly" sliced. I used Cura to slice with standard settings. Maybe you can explain what you mean by "correctly" sliced?

If that's the solution you should tell the Marlin leads about it, they think this can be fixed and thinkyhead was saying that we shouldn't have to lower the slicer resolution for it to print correctly.

I am seeing no solution and yet you just closed a valid report. Can you either explain what the solution is (what resolution is working?) or build without JD ?

**Comment by thierryzoller** [comment]
Also please explain what the hell "correctly issued GCode for the firmware" is supposed to mean.

**Comment by qwewer0** [comment]
If you slice the same modell with PrusaSlicer, then the jitter most likely won't be present. It is big part a slicer issue.

**Comment by le3tspeak** [comment]
In the G codes you added there are circular movements of less than 0.075mm segment length, it is no wonder that nothing will work, especially with the Nano at 72Mhz Core Speed.
thinkyhead said the resolution settings don't match the JD, it doesn't work the way it should.
an example of a resolution setting used by an Ultimaker 3:

Maximum resolution: 0.8333
Maximum motion resolution: 0.75
Maximum deviation 0.05

which I also took on at the FW.

The firmware is optimized for G2 / 3 movements and you try to implement a circle with just one circular movement with the GCode here:
; TYPE: WALL-OUTER

G1 F2400 X120.417 Y126.562 E935.2212
G1 X119.908 Y126.897 E935.23742
G1 X119.393 Y127.218 E935.25356
G1 X118.863 Y127.528 E935.2699
G1 X118.335 Y127.818 E935.28593
G1 X117.79 Y128.099 E935.30225
G1 X117.243 Y128.364 E935.31842
G1 X116.689 Y128.614 E935.33459
G1 X116.134 Y128.847 E935.35061
G1 X115.567 Y129.067 E935.36679
G1 X114.995 Y129.273 E935.38297
G1 X114.418 Y129.463 E935.39913
G1 X113.83 Y129.639 E935.41546
G1 X113.248 Y129.797 E935.43151
G1 X112.658 Y129.942 E935.44767
G1 X112.064 Y130.069 E935.46384
G1 X111.461 Y130.183 E935.48017
G1 X110.867 Y130.28 E935.49618
G1 X110.263 Y130.36 E935.51239
G1 X109.654 Y130.426 E935.52869
G1 X109.054 Y130.474 E935.54471
G1 X108.442 Y130.507 E935.56101
G1 X107.834 Y130.524 E935.5772
G1 X107.231 Y130.525 E935.59324
G1 X106.623 Y130.51 E935.60943
G1 X106.011 Y130.478 E935.62573
G1 X105.411 Y130.432 E935.64174
G1 X104.801 Y130.367 E935.65807
G1 X104.202 Y130.29 E935.67414
G1 X103.601 Y130.194 E935.69033
G1 X103 Y130.082 E935.7066
G1 X102.405 Y129.956 E935.72278
G1 X101.82 Y129.815 E935.73879
G1 X101.233 Y129.657 E935.75497
G1 X100.644 Y129.482 E935.77132
G1 X100.066 Y129.294 E935.78749
G1 X99.499 Y129.092 E935.8035
G1 X98.927 Y128.871 E935.81982
G1 X98.371 Y128.639 E935.83585
G1 X97.811 Y128.388 E935.85218
G1 X97.267 Y128.128 E935.86822
G1 X96.727 Y127.85 E935.88438
G1 X96.189 Y127.557 E935.90068
G1 X95.663 Y127.251 E935.91688
G1 X95.146 Y126.932 E935.93304
G1 X94.641 Y126.602 E935.94909
G1 X94.138 Y126.254 E935.96537
G1 X93.647 Y125.893 E935.98158
G1 X93.171 Y125.526 E935.99758
G1 X92.696 Y125.137 E936.01391
G1 X92.236 Y124.74 E936.03008
G1 X91.785 Y124.331 E936.04628
G1 X91.351 Y123.914 E936.06229
G1 X90.919 Y123.478 E936.07863
G1 X90.503 Y123.035 E936.0948
G1 X90.1 Y122.58 E936.11097
G1 X89.707 Y122.116 E936.12715
G1 X89.331 Y121.646 E936.14316
G1 X88.961 Y121.156 E936.1595
G1 X88.61 Y120.668 E936.17549
G1 X88.266 Y120.159 E936.19184
G1 X87.938 Y119.647 E936.20802
G1 X87.627 Y119.131 E936.22405
G1 X87.324 Y118.597 E936.24039
G1 X87.041 Y118.067 E936.25637
G1 X86.767 Y117.518 E936.2727
G1 X86.51 Y116.967 E936.28888
G1 X86.267 Y116.409 E936.30507
G1 X86.039 Y115.846 E936.32123
G1 X85.826 Y115.277 E936.3374
G1 X85.629 Y114.702 E936.35357
G1 X85.447 Y114.122 E936.36975
G1 X85.28 Y113.542 E936.38581
G1 X85.128 Y112.949 E936.4021
G1 X84.991 Y112.356 E936.41829
G1 X84.871 Y111.761 E936.43444
G1 X84.767 Y111.162 E936.45062
G1 X84.678 Y110.56 E936.46681
G1 X84.605 Y109.956 E936.483
G1 X84.548 Y109.357 E936.49901
G1 X84.507 Y108.745 E936.51533
G1 X84.482 Y108.138 E936.53149
G1 X84.473 Y107.536 E936.54751
G1 X84.481 Y106.927 E936.56372
G1 X84.504 Y106.32 E936.57988
G1 X84.544 Y105.708 E936.5962
G1 X84.598 Y105.108 E936.61223
G1 X84.669 Y104.504 E936.62841
G1 X84.756 Y103.902 E936.6446
G1 X84.859 Y103.303 E936.66077
G1 X84.978 Y102.707 E936.67694
G1 X85.113 Y102.114 E936.69312
G1 X85.264 Y101.52 E936.70943
G1 X85.428 Y100.939 E936.72549
G1 X85.608 Y100.36 E936.74163
G1 X85.804 Y99.785 E936.75779
G1 X86.017 Y99.214 E936.77401
G1 X86.243 Y98.65 E936.79017
G1 X86.484 Y98.092 E936.80635
G1 X86.741 Y97.536 E936.82265
G1 X87.009 Y96.996 E936.83869
G1 X87.296 Y96.455 E936.85498
G1 X87.591 Y95.929 E936.87103
G1 X87.904 Y95.408 E936.8872
G1 X88.23 Y94.896 E936.90335
G1 X88.57 Y94.39 E936.91957
G1 X88.922 Y93.896 E936.93571
G1 X89.287 Y93.41 E936.95188
G1 X89.669 Y92.931 E936.96819
G1 X90.057 Y92.468 E936.98426
G1 X90.459 Y92.013 E937.00041
G1 X90.875 Y91.568 E937.01662
G1 X91.301 Y91.135 E937.03279
G1 X91.738 Y90.714 E937.04893
G1 X92.191 Y90.3 E937.06526
G1 X92.646 Y89.905 E937.08129
G1 X93.116 Y89.519 E937.09748
G1 X93.596 Y89.146 E937.11365
G1 X94.09 Y88.781 E937.12999
G1 X94.583 Y88.438 E937.14597
G1 X95.092 Y88.103 E937.16219
G1 X95.607 Y87.782 E937.17833
G1 X96.137 Y87.472 E937.19467
G1 X96.665 Y87.182 E937.2107
G1 X97.21 Y86.901 E937.22702
G1 X97.757 Y86.636 E937.24319
G1 X98.311 Y86.386 E937.25936
G1 X98.866 Y86.153 E937.27538
G1 X99.433 Y85.933 E937.29156
G1 X100.005 Y85.727 E937.30774
G1 X100.582 Y85.537 E937.3239
G1 X101.17 Y85.361 E937.34023
G1 X101.752 Y85.203 E937.35628
G1 X102.342 Y85.058 E937.37244
G1 X102.936 Y84.931 E937.38861
G1 X103.539 Y84.817 E937.40494
G1 X104.133 Y84.72 E937.42095
G1 X104.737 Y84.64 E937.43716
G1 X105.346 Y84.574 E937.45346
G1 X105.946 Y84.526 E937.46948
G1 X106.558 Y84.493 E937.48578
G1 X107.166 Y84.476 E937.50197
G1 X107.769 Y84.475 E937.51801
G1 X108.377 Y84.49 E937.5342
G1 X108.989 Y84.522 E937.5505
G1 X109.589 Y84.568 E937.56651
G1 X110.199 Y84.633 E937.58284
G1 X110.798 Y84.71 E937.59891
G1 X111.397 Y84.806 E937.61505
G1 X112 Y84.918 E937.63137
G1 X112.595 Y85.044 E937.64755
G1 X113.18 Y85.185 E937.66356
G1 X113.767 Y85.343 E937.67974
G1 X114.356 Y85.518 E937.69609
G1 X114.934 Y85.706 E937.71226
G1 X115.501 Y85.908 E937.72827
G1 X116.068 Y86.127 E937.74445
G1 X116.629 Y86.361 E937.76062
G1 X117.189 Y86.612 E937.77695
G1 X117.733 Y86.872 E937.79299
G1 X118.273 Y87.15 E937.80915
G1 X118.811 Y87.443 E937.82545
G1 X119.337 Y87.749 E937.84165
G1 X119.854 Y88.068 E937.85781
G1 X120.359 Y88.398 E937.87386
G1 X120.858 Y88.743 E937.89
G1 X121.349 Y89.104 E937.90622
G1 X121.829 Y89.474 E937.92234
G1 X122.304 Y89.863 E937.93868
G1 X122.761 Y90.257 E937.95474
G1 X123.211 Y90.665 E937.9709
G1 X123.649 Y91.086 E937.98706
G1 X124.077 Y91.518 E938.00324
G1 X124.493 Y91.961 E938.01941
G1 X124.9 Y92.42 E938.03574
G1 X125.29 Y92.88 E938.05178
G1 X125.669 Y93.354 E938.06793
G1 X126.039 Y93.844 E938.08427
G1 X126.39 Y94.332 E938.10026
G1 X126.734 Y94.841 E938.11661
G1 X127.059 Y95.348 E938.13264
G1 X127.373 Y95.869 E938.14882
G1 X127.676 Y96.403 E938.16516
G1 X127.959 Y96.933 E938.18114
G1 X128.231 Y97.478 E938.19735
G1 X128.488 Y98.028 E938.2135
G1 X128.731 Y98.586 E938.2297
G1 X128.959 Y99.149 E938.24586
G1 X129.172 Y99.718 E938.26203
G1 X129.369 Y100.293 E938.2782
G1 X129.553 Y100.878 E938.29452
G1 X129.72 Y101.458 E938.31058
G1 X129.871 Y102.046 E938.32673
G1 X130.008 Y102.638 E938.3429
G1 X130.128 Y103.234 E938.35908
G1 X130.232 Y103.833 E938.37525
G1 X130.321 Y104.435 E938.39144
G1 X130.395 Y105.044 E938.40777
G1 X130.452 Y105.643 E938.42378
G1 X130.493 Y106.249 E938.43994
G1 X130.518 Y106.857 E938.45613
G1 X130.527 Y107.464 E938.47228
G1 X130.519 Y108.073 E938.48849
G1 X130.496 Y108.68 E938.50465
G1 X130.456 Y109.292 E938.52097
G1 X130.402 Y109.892 E938.537
G1 X130.331 Y110.496 E938.55318
G1 X130.244 Y111.098 E938.56937
G1 X130.141 Y111.697 E938.58554
G1 X130.022 Y112.293 E938.60171
G1 X129.887 Y112.886 E938.61789
G1 X129.736 Y113.48 E938.6342
G1 X129.572 Y114.061 E938.65026
G1 X129.392 Y114.64 E938.6664
G1 X129.196 Y115.215 E938.68256
G1 X128.983 Y115.786 E938.69878
G1 X128.757 Y116.35 E938.71494
G1 X128.516 Y116.908 E938.73112
G1 X128.259 Y117.464 E938.74742
G1 X127.991 Y118.004 E938.76346
G1 X127.704 Y118.545 E938.77975
G1 X127.409 Y119.071 E938.7958
G1 X127.096 Y119.592 E938.81197
G1 X126.77 Y120.104 E938.82812
G1 X126.43 Y120.61 E938.84434
G1 X126.078 Y121.104 E938.86048
G1 X125.713 Y121.59 E938.87665
G1 X125.331 Y122.069 E938.89296
G1 X124.943 Y122.532 E938.90903
G1 X124.541 Y122.987 E938.92518
G1 X124.125 Y123.432 E938.94139
G1 X123.699 Y123.865 E938.95756
G1 X123.262 Y124.286 E938.9737
G1 X122.809 Y124.7 E938.99003
G1 X122.354 Y125.095 E939.00606
G1 X121.884 Y125.481 E939.02225
G1 X121.709 Y125.617 E939.02814
G0 F2160 X121.404 Y125.854
G0 X120.91 Y126.219

and in the file added by me, which is adapted for the FW, the many G code looks like a circular movement from you:
; TYPE: WALL-OUTER
G2 X101.444 Y114.965 I-8.725 J4.074 E43.79026 F2400
G2 X116.293 Y103.870 I5.868 J-7.630 E45.08598
G0 F2160 X116.039 Y103.255
M204 S5000
M205 X30 Y30
G0 F6000 X115.947 Y103.078
G0 X116.415 Y102.835
G1 F3000 E39.08598
G0 F6000 X118.073 Y108.003
G0 X116.021 Y107.872
G0 X129.041 Y117.833
G0 X127.159 Y116.961
G0 X126.821 Y118.077

you might notice the differences too, right?

**Comment by le3tspeak** [comment]
and a second example of customized G code for the FW here is the first skirt line of your G code:

;TYPE:SKIRT
G1 F3000 E0
G1 F2400 X109.492 Y81.115 E0.03041
G1 X110.29 Y81.188 E0.07199
G1 X110.87 Y81.255 E0.10229
G1 X111.676 Y81.372 E0.14454
G1 X112.358 Y81.489 E0.18045
G1 X112.933 Y81.604 E0.21087
G1 X113.753 Y81.79 E0.2545
G1 X114.379 Y81.95 E0.28802
G1 X114.978 Y82.119 E0.32032
G1 X115.696 Y82.342 E0.35933
G1 X116.434 Y82.594 E0.39979
G1 X116.951 Y82.785 E0.42839
G1 X117.725 Y83.095 E0.47165
G1 X118.264 Y83.329 E0.50214
G1 X118.951 Y83.647 E0.54141
G1 X119.617 Y83.977 E0.57998
G1 X120.122 Y84.244 E0.60962
G1 X120.818 Y84.636 E0.65106
G1 X121.377 Y84.971 E0.68488
G1 X121.996 Y85.364 E0.72292
G1 X122.546 Y85.734 E0.75732
G1 X123.213 Y86.209 E0.7998
G1 X123.642 Y86.533 E0.8277
G1 X124.28 Y87.041 E0.87001
G1 X124.776 Y87.457 E0.9036
G1 X125.285 Y87.91 E0.93895
G1 X125.823 Y88.411 E0.9771
G1 X126.275 Y88.856 E1.01001
G1 X126.792 Y89.392 E1.04865
G1 X127.292 Y89.937 E1.08702
G1 X127.685 Y90.392 E1.11822
G1 X128.178 Y90.991 E1.15847
G1 X128.584 Y91.513 E1.19278
G1 X128.986 Y92.059 E1.22796
G1 X129.44 Y92.71 E1.26914
G1 X129.761 Y93.195 E1.29932
G1 X130.154 Y93.83 E1.33807
G1 X130.523 Y94.462 E1.37604
G1 X130.862 Y95.075 E1.41239
G1 X131.126 Y95.588 E1.44232
G1 X131.503 Y96.367 E1.48723
G1 X131.751 Y96.916 E1.51848
G1 X132.019 Y97.554 E1.55439
G1 X132.283 Y98.229 E1.59199
G1 X132.508 Y98.856 E1.62656
G1 X132.755 Y99.607 E1.66758
G1 X132.931 Y100.193 E1.69932
G1 X133.128 Y100.916 E1.7382
G1 X133.274 Y101.517 E1.77029
G1 X133.447 Y102.314 E1.81261
G1 X133.562 Y102.927 E1.84497
G1 X133.677 Y103.638 E1.88234
G1 X133.762 Y104.272 E1.91553
G1 X133.848 Y105.064 E1.95687
G1 X133.895 Y105.644 E1.98706
G1 X133.939 Y106.454 E2.02915
G1 X133.957 Y107.106 E2.06299
G1 X133.958 Y107.807 E2.09936
G1 X133.942 Y108.461 E2.13331
G1 X133.901 Y109.269 E2.17528
G1 X133.856 Y109.848 E2.20542
G1 X133.773 Y110.64 E2.24674
G1 X133.688 Y111.28 E2.28023
G1 X133.575 Y111.994 E2.31774
G1 X133.464 Y112.597 E2.34955
G1 X133.293 Y113.401 E2.3922
G1 X133.149 Y114 E2.42417
G1 X132.954 Y114.725 E2.46312
G1 X132.781 Y115.311 E2.49483
G1 X132.533 Y116.068 E2.53616
G1 X132.315 Y116.684 E2.57006
G1 X132.051 Y117.367 E2.60805
G1 X131.784 Y118.008 E2.64408
G1 X131.541 Y118.551 E2.67495
G1 X131.162 Y119.341 E2.72041
G1 X130.903 Y119.846 E2.74986
G1 X130.565 Y120.466 E2.7865
G1 X130.195 Y121.102 E2.82468
G1 X129.812 Y121.723 E2.86253
G1 X129.484 Y122.225 E2.89365
G1 X129.04 Y122.867 E2.93415
G1 X128.632 Y123.422 E2.96989
G1 X128.233 Y123.939 E3.00377
G1 X127.738 Y124.545 E3.04437
G1 X127.352 Y124.994 E3.07509
G1 X126.852 Y125.544 E3.11366
G1 X126.333 Y126.087 E3.15263
G1 X125.89 Y126.525 E3.18496
G1 X125.34 Y127.041 E3.22409
G1 X124.84 Y127.486 E3.25882
G1 X124.354 Y127.898 E3.29188
G1 X123.643 Y128.466 E3.33909
G1 X123.212 Y128.791 E3.3671
G1 X122.615 Y129.217 E3.40515
G1 X122.069 Y129.588 E3.43941
G1 X121.447 Y129.986 E3.47772
G1 X120.9 Y130.317 E3.51089
G1 X120.19 Y130.718 E3.5532
G1 X119.695 Y130.983 E3.58233
G1 X119.033 Y131.314 E3.62074
G1 X118.331 Y131.641 E3.66092
G1 X117.808 Y131.87 E3.69054
G1 X117.033 Y132.183 E3.73391
G1 X116.51 Y132.379 E3.76289
G1 X115.782 Y132.63 E3.80284
G1 X115.066 Y132.855 E3.84178
G1 X114.449 Y133.031 E3.87507
G1 X113.844 Y133.188 E3.90751
G1 X113.005 Y133.379 E3.95215
G1 X112.454 Y133.493 E3.98135
G1 X111.757 Y133.615 E4.01806
G1 X110.961 Y133.733 E4.05981
G1 X110.371 Y133.804 E4.09065
G1 X109.578 Y133.878 E4.13197
G1 X108.99 Y133.918 E4.16255
G1 X108.233 Y133.949 E4.20186
G1 X107.543 Y133.96 E4.23767
G1 X106.855 Y133.952 E4.27337
G1 X106.094 Y133.922 E4.31288
G1 X105.509 Y133.885 E4.3433
G1 X104.71 Y133.812 E4.38492
G1 X104.13 Y133.744 E4.41522
G1 X103.325 Y133.628 E4.45742
G1 X102.642 Y133.51 E4.49339
G1 X102.069 Y133.396 E4.5237
G1 X101.247 Y133.21 E4.56743
G1 X100.626 Y133.052 E4.60068
G1 X100.018 Y132.88 E4.63346
G1 X99.304 Y132.658 E4.67226
G1 X98.566 Y132.406 E4.71272
G1 X98.049 Y132.215 E4.74132
G1 X97.275 Y131.905 E4.78458
G1 X96.736 Y131.671 E4.81507
G1 X96.049 Y131.353 E4.85434
G1 X95.383 Y131.023 E4.89291
G1 X94.878 Y130.756 E4.92255
G1 X94.182 Y130.364 E4.964
G1 X93.623 Y130.029 E4.99781
G1 X93.004 Y129.636 E5.03585
G1 X92.454 Y129.266 E5.07025
G1 X91.785 Y128.789 E5.11288
G1 X91.357 Y128.466 E5.1407
G1 X90.718 Y127.957 E5.18309
G1 X90.221 Y127.539 E5.21678
G1 X89.72 Y127.095 E5.25152
G1 X89.174 Y126.587 E5.29021
G1 X88.728 Y126.148 E5.32268
G1 X88.205 Y125.605 E5.3618
G1 X87.708 Y125.063 E5.39995
G1 X87.315 Y124.608 E5.43115
G1 X86.822 Y124.008 E5.47144
G1 X86.415 Y123.486 E5.50579
G1 X86.013 Y122.941 E5.54092
G1 X85.559 Y122.287 E5.58223
G1 X85.239 Y121.804 E5.61229
G1 X84.848 Y121.174 E5.65077
G1 X84.478 Y120.542 E5.68876
G1 X84.137 Y119.925 E5.72534
G1 X83.873 Y119.411 E5.75532
G1 X83.496 Y118.632 E5.80023
G1 X83.249 Y118.084 E5.83142
G1 X82.982 Y117.449 E5.86716
G1 X82.715 Y116.764 E5.9053
G1 X82.494 Y116.149 E5.93921
G1 X82.245 Y115.393 E5.98051
G1 X82.069 Y114.807 E6.01226
G1 X81.872 Y114.084 E6.05114
G1 X81.726 Y113.486 E6.08308
G1 X81.553 Y112.681 E6.1258
G1 X81.439 Y112.079 E6.15759
G1 X81.323 Y111.362 E6.19527
G1 X81.238 Y110.728 E6.22846
G1 X81.152 Y109.936 E6.2698
G1 X81.105 Y109.356 E6.29999
G1 X81.061 Y108.546 E6.34208
G1 X81.043 Y107.895 E6.37587
G1 X81.042 Y107.192 E6.41235
G1 X81.058 Y106.538 E6.44629
G1 X81.099 Y105.73 E6.48827
G1 X81.144 Y105.151 E6.5184
G1 X81.227 Y104.359 E6.55972
G1 X81.312 Y103.719 E6.59322
G1 X81.424 Y103.005 E6.63072
G1 X81.536 Y102.402 E6.66254
G1 X81.707 Y101.599 E6.70514
G1 X81.853 Y100.994 E6.73743
G1 X82.044 Y100.279 E6.77583
G1 X82.22 Y99.688 E6.80783
G1 X82.466 Y98.933 E6.84903
G1 X82.686 Y98.314 E6.88311
G1 X82.949 Y97.633 E6.92099
G1 X83.218 Y96.988 E6.95725
G1 X83.456 Y96.453 E6.98763
G1 X83.839 Y95.657 E7.03346
G1 X84.095 Y95.156 E7.06266
G1 X84.433 Y94.536 E7.0993
G1 X84.806 Y93.895 E7.13777
G1 X85.189 Y93.275 E7.17559
G1 X85.516 Y92.775 E7.20659
G1 X85.962 Y92.132 E7.24719
G1 X86.366 Y91.58 E7.28268
G1 X86.765 Y91.062 E7.31661
G1 X87.262 Y90.454 E7.35735
G1 X87.648 Y90.006 E7.38803
G1 X88.149 Y89.454 E7.42671
G1 X88.667 Y88.914 E7.46554
G1 X89.11 Y88.475 E7.4979
G1 X89.657 Y87.962 E7.53681
G1 X90.159 Y87.513 E7.57175
G1 X90.649 Y87.1 E7.605
G1 X91.357 Y86.534 E7.65203
G1 X91.787 Y86.209 E7.68
G1 X92.385 Y85.782 E7.71813
G1 X92.932 Y85.411 E7.75242
G1 X93.553 Y85.014 E7.79066
G1 X94.104 Y84.681 E7.82407
G1 X94.807 Y84.283 E7.86598
G1 X95.307 Y84.016 E7.89539
G1 X95.967 Y83.686 E7.93368
G1 X96.672 Y83.358 E7.97402
G1 X97.188 Y83.132 E8.00325
G1 X97.966 Y82.816 E8.04682
G1 X98.496 Y82.619 E8.07616
G1 X99.221 Y82.369 E8.11595
G1 X99.933 Y82.145 E8.15468
G1 X100.553 Y81.968 E8.18813
G1 X101.157 Y81.812 E8.2205
G1 X101.99 Y81.621 E8.26484
G1 X102.552 Y81.506 E8.29461
G1 X103.244 Y81.385 E8.33106
G1 X104.039 Y81.267 E8.37276
G1 X104.63 Y81.196 E8.40364
G1 X105.422 Y81.122 E8.44492
G1 X106.012 Y81.082 E8.4756
G1 X106.767 Y81.051 E8.51481
G1 X107.457 Y81.04 E8.55061
G1 X108.146 Y81.048 E8.58636
G1 X108.241 Y81.052 E8.5913
G0 F2160 X108.907 Y81.078
M204 S5000
M205 X30 Y30

and here adapted to the FW:
; TYPE: SKIRT
G1 F3000 E0
G3 X132.282 Y98.228 I-1.400 J26.415 E1.59198 F2400
G3 X125.890 Y126.525 I-24.788 J9.269 E3.18496
G3 X97.275 Y131.905 I-18.389 J-19.021 E4.78457
G3 X81.043 Y107.894 I10.232 J-24.409 E6.37586
G3 X96.671 Y83.358 I26.454 J-0.395 E7.97402
G3 X108.240 Y81.052 I10.810 J24.063 E8.59130
G0 F2160 X108.907 Y81.078
M204 S5000
M205 X30 Y30

**Comment by thierryzoller** [comment]
Thank you, that explains a lot. I do not know of any slicer that produces G2/G3 moves. Which one should we use (or supports arc) ?

As to Maximum Resolution : If I set Max Resolution to your settings above, the stutter will be less?

**Comment by thierryzoller** [comment]
> If you slice the same modell with PrusaSlicer, then the jitter most likely won't be present. It is big part a slicer issue.

I also noticed this but didn't know why this is the case.

**Comment by thierryzoller** [comment]
I resliced it with the CURA profile you uploaded, its 6MB and the settings are

-Maximum Travel Resolution iss 0.88
-Deviation set 0.05

Is that going to reduce the issue?

**Comment by thierryzoller** [comment]
The settings you listed `Maximum resolution: 0.8333
Maximum motion resolution: 0.75
Maximum deviation 0.05`

Are not in the CURA profile you uploaded, is this an error?

**Comment by thierryzoller** [comment]
For those having the same problem. I disabled JD enabled, Classic Jerk and S-Curve and the problem is gone. One notices a lot of small movements but no judder.

**Comment by thierryzoller** [comment]
update: https://github.com/MarlinFirmware/Marlin/issues/17342#issuecomment-645493437

When using the newest bugfix-2.0.x, you can now change the config parameter

#define JD_HANDLE_SMALL_SEGMENTS
in Configuration.h to

//#define JD_HANDLE_SMALL_SEGMENTS
and thereby deactivate the code which is causing most (all?) of the stuttering and surface blobs. This is a workaround until an actual fix may be implemented, which - I guess - is at least a couple of months away.

**Comment by le3tspeak** [comment]
https://github.com/le3tspeak/Marlin-2.0.X-MKS-Robin-Nano/commit/41f88f707eebcb65566a8c9d07b478c435780168
