### ISSUE TITLE
[BUG] Enabling power loss recovery freeze the printer!

### ISSUE THREAD

**Issue by enthropy92** [le3tspeak/Marlin-2.0.X-MKS-Robin-Nano#20]
### My Configurations

**Required:** Please include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by le3tspeak** [comment]
It does not work with the Nano it is also not without reason (Creality3D) in the top of the Power Loss

**Comment by enthropy92** [comment]
Ok thank you :)
