### ISSUE TITLE
TMC2208 SW Serial wiring wrong

### ISSUE THREAD

**Issue by JoLink11** [le3tspeak/Marlin-2.0.X-MKS-Robin-Nano#22]
### Description

Wiring of the X,Y,Z Stepper UART is pointing to PA6 PA1 GND,
it should be PA3(EN) PA6(STEP) PA1(DIR).

#### Additional Information
Shift in the picture these three pins one pin to the left.

P.S.:
Thanks for your awesome work for the TwoTrees printers!

**Comment by le3tspeak** [comment]
Thanks for the tip I did not notice, change is coming this afternoon
