### ISSUE TITLE
[FR] Enable PID TUNING in Menu

### ISSUE THREAD

**Issue by thierryzoller** [le3tspeak/Marlin-2.0.X-MKS-Robin-Nano#25]
Good experience with the inbuilt Auto PID tuning option :  I recommend enabling it in Menu 👍 
#if ENABLED(PIDTEMP)
  #define PID_EDIT_MENU    
  #define PID_AUTOTUNE_MENU  
  //#define PID_PARAMS_PER_HOTEND // Uses separate PID parameters for each extruder (useful for mismatched extruders)

**Comment by le3tspeak** [comment]
Is in the planning and coming has to be adjusted that you can set a temp is currently FIX set to 150 °

**Comment by thierryzoller** [comment]
I think you may be mistaken, if you select the menu (set to 150) you can set it to any temperature you want. I did Pid tune to the temp I set :)

**Comment by thierryzoller** [comment]
https://github.com/le3tspeak/Marlin-2.0.X-MKS-Robin-Nano/commit/2113ea760a9f1ca38eb746d11f14f45f7ab4444e
