### ISSUE TITLE
PID_EXTRUSION_SCALING does not work ?

### ISSUE THREAD

**Issue by user32rtu** [le3tspeak/Marlin-2.0.X-MKS-Robin-Nano#30]
Hello ! I have a question about "PID_EXTRUSION_SCALING".
When calibrating the filament feed, I found that the feed becomes smaller as the feed speed increases. I decided to compensate for the decrease in feed by increasing the temperature. I used "AUTOTEMP". With increasing print speed, I saw an increase in temperature. Then I turned off "AUTOTEMP" and turned on "PID_EXTRUSION_SCALING". With increasing print speed, the temperature did not change. I tried increasing "Kc = 150", but it did not give any effect.

**Comment by le3tspeak** [comment]
PID_EXTRUSION_SCALING also does not raise the temperatures.
PID_EXTRUSION_SCALING is for adjusting the PID values during a print with nozzles over 0.6.

For temperatures is AUTO_TEMP

Linear Advance is used to adapt the lines.

**Comment by user32rtu** [comment]
Thanks for the info.
Please tell me what is AUTOTEMP_OLDWEIGHT? How to use it?

**Comment by thierryzoller** [comment]
You would need to ask Marlin for support, this is just a fork.

**Comment by thierryzoller** [comment]
https://github.com/MarlinFirmware/Marlin/issues/11157
