### ISSUE TITLE
S-Curve with LA

### ISSUE THREAD

**Issue by Miraculix200** [le3tspeak/Marlin-2.0.X-MKS-Robin-Nano#6]
It's probably best to deactivate S_CURVE_ACCELERATION in Configuration.h. Because it doesn't play well with LIN_ADVANCE_K value >0. Or actually LIN_ADVANCE doesn't play well with S_CURVE_ACCELERATION (it simply ignores that it's activated). 

In newer bugfix versions it won't even compile with both options enabled, unless you also enable EXPERIMENTAL_SCURVE (which probably does nothing except ignoring the conflict)

**Comment by le3tspeak** [comment]
https://github.com/le3tspeak/Marlin-2.0.X-MKS-Robin-Nano/commit/23ffb0de14cce62aed219482469df7383224bd75
