### ISSUE TITLE
bilinear mesh doesn't work don't compensate 

### ISSUE THREAD

**Issue by ivograca** [le3tspeak/Marlin-2.0.X-MKS-Robin-Nano#9]
### Bug Description

bilinear mesh dosn´t work dont make any compensation on Z.

### My Configurations

[Configuration.zip](https://github.com/le3tspeak/Marlin-2.0.X-MKS-Robin-Nano/files/4688085/Configuration.zip)

### Steps to Reproduce

1. [First Step] activate bilinear or use my file 
2. [Second Step] you need to have a sensor use G29 after G28 on inicial Gcode  
3. [and so on...] print and see that z doesn´t compensate 

**Expected behavior:** Compensation of Z 

**Actual behavior:** the z either moves very little or does not move regardless of whether the table is more or less misaligned

#### Additional Information 
Marlin 2.0.5.3
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by le3tspeak** [comment]
No Configuration.h and Configuration_adv.h files added.
Which version?

**Comment by ivograca** [comment]
i have edit and update informations thanks for your work

**Comment by le3tspeak** [comment]
Enable DEBUG_LEVELING_FEATURE and M114_DETAIL and re-flash the firmware.
Connect to your printer from host software such as Cura, Printrun or Repetier Host.
Issue the command M111 S247 to enable maximum logging.
Perform a G28 to do your standard homing procedure.
Do a G29 to probe the bed. This will also enable bed leveling.
Copy the log output into a .TXT file and attach it to your next reply.
Repeat this procedure, if needed, to demonstrate inconsistencies. From these logs we should hopefully get a better idea of what's going on with your machine.

**Comment by le3tspeak** [comment]
Please be so good and try the Branch MKS Robin Nano I have revised the whole code and from now on only for the branch support otherwise it will be too confusing for me and your error should not happen anymore

https://github.com/le3tspeak/Marlin-2.0.X-MKS-Robin-Nano/tree/MKS-Robin-Nano
